//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Invoice()
        {
            this.tb_Invoice_Detail = new HashSet<tb_Invoice_Detail>();
        }
    
        public string InvoiceID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string PaymentID { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public string TableID { get; set; }
        public string EmployeeID { get; set; }
    
        public virtual tb_Customer tb_Customer { get; set; }
        public virtual tb_DiningTable tb_DiningTable { get; set; }
        public virtual tb_Employee tb_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Invoice_Detail> tb_Invoice_Detail { get; set; }
        public virtual tb_Payment tb_Payment { get; set; }
    }
}
