//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OverTime
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> OvertimeDate { get; set; }
        public Nullable<int> OvertimeHours { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> coeffSalary { get; set; }
    
        public virtual tb_Employee tb_Employee { get; set; }
    }
}
