//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Product()
        {
            this.tb_Invoice_Detail = new HashSet<tb_Invoice_Detail>();
            this.tb_Rating = new HashSet<tb_Rating>();
        }
    
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string AliasName { get; set; }
        public Nullable<double> Price { get; set; }
        public string ProductImage { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string Description { get; set; }
        public string CategoryID { get; set; }
    
        public virtual tb_Category tb_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Invoice_Detail> tb_Invoice_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Rating> tb_Rating { get; set; }
    }
}
