//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Rating
    {
        public string reviewID { get; set; }
        public string contentDetail { get; set; }
        public Nullable<int> rating { get; set; }
        public string customerID { get; set; }
        public string productID { get; set; }
        public Nullable<System.DateTime> timeReview { get; set; }
    
        public virtual tb_Customer tb_Customer { get; set; }
        public virtual tb_Product tb_Product { get; set; }
    }
}
